plugins:
  "@bercow/link-adjacent": {}
  "@bercow/prettier":
    prettier-options: "."
  "@bercow/eslint": {}
  "@bercow/spawn":
    command: npx
    command-win32: npx.cmd
    argv:
      - c8
      - --100
      - --include
      - $RELATIVE_MAIN_PATH
      - --
      - node
      - --loader=ts-node/esm
      - --unhandled-rejections=strict
      - $RELATIVE_TEST_PATH
