root: true
extends:
  - eslint:recommended
  - plugin:import/recommended
globals:
  console: readonly
  URL: readonly
  URLSearchParams: readonly
env:
  es6: true
  es2017: true
rules:
  # import/no-extraneous-dependencies:
  #   - error
  #   - devDependencies: true
  no-empty-pattern: off
  no-control-regex: off
  no-debugger:
    - warn
  no-console:
    - warn
  no-unused-vars:
    - error
    - { args: none }
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
