type: object
additionalProperties: false
minProperties: 42
properties:
  socket:
    $ref: socket
  heartbeat:
    $ref: heartbeat
  threshold:
    $ref: threshold
  scenario:
    $ref: regexp
  scenarios:
    type: array
    items:
      type: object
      additionalProperties: false
      required:
        - key
        - value
        - base
      properties:
        key:
          type: string
        value:
          $ref: configuration-external
        base:
          $ref: url
  recursive-process-recording:
    type: boolean
  command:
    $ref: command-cooked
  command-win32:
    $ref: command-cooked
  command-options:
    $ref: command-options-cooked
  validate:
    type: object
    additionalProperties: false
    required:
      - message
      - appmap
    properties:
      message:
        type: boolean
      appmap:
        type: boolean
  agent:
    anyOf:
      - const: null
      - $ref: agent-cooked
  repository:
    $ref: repository
  log:
    $ref: log-cooked
  host:
    const: localhost
  session:
    anyOf:
      - const: null
      - $ref: session
  sessions:
    $ref: regexp
  proxy-port:
    $ref: port-proxy
  trace-port:
    $ref: port-cooked
  trace-protocol:
    const: TCP
  http-switch:
    $ref: url-component
  track-port:
    $ref: port-cooked
  track-protocol:
    const: HTTP/1.1
  intercept-track-port:
    $ref: regexp
  intercept-track-protocol:
    const: HTTP/1.1
  recorder:
    anyOf:
      - const: null
      - $ref: recorder
  inline-source:
    type: boolean
  postmortem-function-exclusion:
    type: boolean
    nullable: true
  hooks:
    type: object
    additionalProperties: false
    required:
      - cjs
      - esm
      - eval
      - apply
      - http
      - mysql
      - pg
      - sqlite3
    properties:
      cjs:
        type: boolean
      esm:
        type: boolean
      eval:
        type: object
        additionalProperties: false
        properties:
          hidden:
            $ref: identifier
          aliases:
            type: array
            items:
              type: string
      apply:
        anyOf:
          - const: null
          - $ref: identifier
      http:
        type: boolean
      mysql:
        type: boolean
        nullable: true
      pg:
        type: boolean
        nullable: true
      sqlite3:
        type: boolean
        nullable: true
  ordering:
    $ref: ordering
  default-process:
    $ref: process
  processes:
    type: array
    items:
      type: array
      minItems: 2
      maxItems: 2
      items:
        - $ref: matcher-cooked
        - $ref: process
  main:
    anyOf:
      - const: null
      - $ref: url
  engine:
    type: string
    nullable: true
  language:
    $ref: language
  default-package:
    $ref: module-cooked
  packages:
    type: array
    items:
      type: array
      minItems: 2
      maxItems: 2
      items:
        - $ref: matcher-cooked
        - $ref: module-cooked
  exclude:
    $ref: exclude-cooked
  collapse-package-hierachy:
    type: boolean
  recording:
    anyOf:
      - const: null
      - $ref: recording-object
  serialization:
    allOf:
      - $ref: serialization
      - type: object
        required:
          - maximum-print-length
          - maximum-properties-length
          - impure-printing
          - impure-constructor-naming
          - impure-array-inspection
          - impure-error-inspection
          - impure-hash-inspection
  pruning:
    type: boolean
  appmap_dir:
    $ref: url
  appmap_file:
    anyOf:
      - $ref: basename
      - const: null
  name:
    type: string
    nullable: true
  map-name:
    type: string
    nullable: true
  feature:
    type: string
    nullable: true
  feature-group:
    type: string
    nullable: true
  labels:
    type: array
    items:
      type: string
  frameworks:
    type: array
    items:
      $ref: name-version
