type: object
properties:
  agent:
    $ref: agent
  repository:
    $ref: repository
  scenarios:
    type: object
    additionalProperties: false
    patternProperties:
      ^:
        $ref: configuration-external
  scenario:
    $ref: regexp
  recursive-process-recording:
    type: boolean
  command:
    $ref: command
  command-win32:
    $ref: command
  command-options:
    $ref: command-options
  validate:
    type: object
    additionalProperties: false
    properties:
      message:
        type: boolean
      appmap:
        type: boolean
  log:
    $ref: log
  host:
    const: localhost
  session:
    $ref: session
  sessions:
    $ref: regexp
  proxy-port:
    $ref: port-proxy
  trace-port:
    $ref: port
  trace-protocol:
    const: TCP
  http-switch:
    $ref: url-component
  track-port:
    $ref: port
  track-protocol:
    const: HTTP/1.1
  intercept-track-port:
    $ref: regexp
  intercept-track-protocol:
    const: HTTP/1.1
  socket:
    $ref: socket
  heartbeat:
    $ref: heartbeat
  threshold:
    $ref: threshold
  recorder:
    $ref: recorder
  inline-source:
    type: boolean
  postmortem-function-exclusion:
    type: boolean
    nullable: true
  hooks:
    type: object
    additionalProperties: false
    properties:
      cjs:
        type: boolean
      esm:
        type: boolean
      eval:
        anyOf:
          - type: boolean
          - type: object
            additionalProperties: false
            properties:
              hidden:
                $ref: identifier
              aliases:
                type: array
                items:
                  type: string
      apply:
        anyOf:
          - type: boolean
          - const: null
          - $ref: identifier
      http:
        type: boolean
      mysql:
        type: boolean
        nullable: true
      pg:
        type: boolean
        nullable: true
      sqlite3:
        type: boolean
        nullable: true
  ordering:
    $ref: ordering
  default-process:
    anyOf:
      - type: boolean
      - $ref: process
  processes:
    anyOf:
      - $ref: matcher-process
      - type: array
        items:
          $ref: matcher-process
  main:
    $ref: path
  engine:
    type: string
  language:
    $ref: language
  default-package:
    $ref: module
  packages:
    anyOf:
      - $ref: matcher-module
      - type: array
        items:
          $ref: matcher-module
  exclude:
    $ref: exclude
  collapse-package-hierachy:
    type: boolean
  recording:
    $ref: recording
  serialization:
    $ref: serialization
  pruning:
    type: boolean
  appmap_dir:
    $ref: path
  appmap_file:
    $ref: basename
  name:
    type: string
  map-name:
    type: string
  feature:
    type: string
  feature-group:
    type: string
  labels:
    type: array
    items:
      type: string
  frameworks:
    type: array
    items:
      $ref: name-version
