export const server = [
  // 'logger',
  // 'config',
  // 'git',
  // 'namespace',
  // 'file',
  // 'instrument/location',
  // 'instrument/visit',
  // 'instrument/visit-class',
  // 'instrument/visit-closure',
  // 'instrument/visit-expression',
  // 'instrument/visit-identifier',
  // 'instrument/visit-pattern',
  // 'instrument/visit-program',
  // 'instrument/visit-statement',
  // 'instrument/index',
  // 'appmap',
  // 'dispatcher',
  'response/http1',
  'response/http2',
  'response/fork',
  'response/index',
  'main',
  'inline/response',
  'inline/channel',
  'inline/main',
];

export const client = [
  'es2015/script',
  'es2015/node/request/curl-sync',
  'es2015/node/request/fork-async',
  'es2015/node/request/http1-async',
  'es2015/node/request/http2-async',
  'es2015/node/request/http3-async',
  'es2015/node/channel',
  'es2015/node/setup',
  'es2015/node/hook-cjs',
  'es2015/node/hook-esm',
  'es2015/node/main-cjs',
  'es2015/node/main-esm',
  'es2015/node/main-both',
];
