export const server = [
  // 'assert',
  // 'logger',
  // 'either',
  // 'either-map',
  // 'validate',
  // 'configuration/cwd',
  // 'configuration/git',
  'configuration/specifier',
  'configuration/field',
  'configuration/index',
  'instrument/location',
  'instrument/visit',
  'instrument/visit-class',
  'instrument/visit-closure',
  'instrument/visit-expression',
  'instrument/visit-identifier',
  'instrument/visit-pattern',
  'instrument/visit-program',
  'instrument/visit-statement',
  'instrument/index',
  'appmap/file',
  'appmap/recording',
  'appmap/index',
  'dispatching',
  'response/messaging',
  'response/http1',
  'response/http2',
  'response/http3',
  'response/index',
  'index',
  'inline',
  'main',
];

export const client = [
  // 'es2015/runtime',
  // 'es2015/recorder',
  // 'es2015/appmap',
  // 'es2015/node14x/channel/request-sync/messaging',
  // 'es2015/node14x/channel/request-sync/curl',
  // 'es2015/node14x/channel/request-sync/http1',
  // 'es2015/node14x/channel/request-sync/http2',
  // 'es2015/node14x/channel/request-sync/http3',
  // 'es2015/node14x/channel/request/messaging',
  // 'es2015/node14x/channel/request/http1',
  // 'es2015/node14x/channel/request/http2',
  // 'es2015/node14x/channel/request/http3',
  // 'es2015/node14x/channel/index',
  // 'es2015/node14x/hook/cjs',
  // 'es2015/node14x/hook/esm',
  // 'es2015/node14x/hook/index',
  // 'es2015/node14x/index',
  // 'es2015/node14x/plugin/check-version',
  // 'es2015/node14x/plugin/env',
  // 'es2015/node14x/plugin/mono-main',
  // 'es2015/node14x/plugin/mono-bin',
];
