export const server = [
  'logger',
  'config',
  'git',
  'namespace',
  'file',
  'instrument/location',
  'instrument/visit',
  'instrument/visit-class',
  'instrument/visit-closure',
  'instrument/visit-expression',
  'instrument/visit-identifier',
  'instrument/visit-pattern',
  'instrument/visit-program',
  'instrument/visit-statement',
  'instrument/index',
  'appmap',
  'inline',
];

export const client = [
  'es2015/script',
  'es2015/node/channel/test',
  'es2015/node/setup',
  'es2015/node/hook-cjs',
  'es2015/node/hook-esm',
  'es2015/node/main-cjs',
  'es2015/node/main-esm',
  'es2015/node/main-both',
];
